from selenium import webdriver
driver = webdriver.Chrome("E:\\Selenium_Project\\browserdriver\\chromedriver_win32\\chromedriver.exe")
driver.maximize_window()
driver.get("https://paytm.com/")
driver.implicitly_wait(30)
driver.find_element_by_class_name("_3ac-").click()
driver.switch_to.frame(driver.find_element_by_xpath(".//iframe"))
driver.find_element_by_xpath(".//span[@event-category='login_v2']").click()
driver.find_element_by_xpath(".//li[contains(text(),'Sign Up')]").click()
driver.find_element_by_name("mobileNumber").send_keys("7058704461")
driver.find_element_by_name("loginPassword").send_keys("up93e5908")
driver.find_element_by_name("email").send_keys("jitsolution19@gmail.com")
# driver.find_element_by_xpath(".//input[@name='username']").send_keys("7058704461")
# driver.find_element_by_xpath(".//input[@name='password']").send_keys("up93e5908")